<?php
/**
*ClipVilla Video Producer
*
*The ClipVilla Video Producer's code is created by ClipVilla GmbH. 
*If the code is completely or partially changed by a third party all guarantee and warranty claims against ClipVilla GmbH will be invalidated.
*
* NOTICE OF LICENSE
*
* This source file is subject to the GNU General Public License (GPLv3)
* It is available through the world-wide-web at this URL:
* http://www.gnu.org/licenses/quick-guide-gplv3.html.en
*/
?>


<img style="float:right;" src="<?php echo $this->getLogo(); ?>" width="365px" />
<p style="font-weight:bold">Are you enjoying your experience with the ClipVilla Video Producer?</p>

<p>
	<strong>Need a quick start?</strong><br/>
	If you have difficulties getting started, simply watch our 3-minute <a href="http://videoproducer.clipvilla.com/#Howto" target="_blank">support video</a> on how to use the ClipVilla Video Producer. 
</p>
<p>
    We have so much more for you:<br/>
    <a href="http://videoproducer.clipvilla.com/#Price" target="_blank">Click here</a> to book your package offer and get your video contingent and templates to start right
    off with the production. Simply select a video template, royalty free music and insert text modules!<br/>
    For a monthly investment starting at as little as 99 $!
</p>

<p>
    Or choose our <a href="http://videoproducer.clipvilla.com/#Price" target="_blank">customized package</a> and the ClipVilla Video Producer will be adjusted to your
    individual system requirements. A custom-made video-template, synthesization with your magento-data,
    motion, animation and text voice over, global shop attributes and up to 10 product categories included!
</p>

<p>
	<strong>You need support for the Video Producer?</strong><br/>
	For technical support please contact <a href="mailto:techsupport@clipvilla.com?Subject=Customized%20Extension" target="_top">techsupport@clipvilla.com</a>
</p>