<?php
/**
*ClipVilla Video Producer
*
*The ClipVilla Video Producer's code is created by ClipVilla GmbH. 
*If the code is completely or partially changed by a third party all guarantee and warranty claims against ClipVilla GmbH will be invalidated.
*
* NOTICE OF LICENSE
*
* This source file is subject to the GNU General Public License (GPLv3)
* It is available through the world-wide-web at this URL:
* http://www.gnu.org/licenses/quick-guide-gplv3.html.en
*/
?>
<?php
/**
 * @see ClipVilla_MorI_Block_Adminhtml_ManageVideos_Popup
 */
?>
<div style="margin-top:6px; margin-left:5px; max-width:795px;">
    <video id="product_video" class="video-js vjs-default-skin vjs-big-play-centered"
           controls preload="auto" width="auto" height="auto"
           data-setup='{}'>
        <source src="<?php echo $this->getVideo(); ?>" type='video/mp4' />
    </video>
</div>