<?php
/**
*ClipVilla Video Producer
*
*The ClipVilla Video Producer's code is created by ClipVilla GmbH. 
*If the code is completely or partially changed by a third party all guarantee and warranty claims against ClipVilla GmbH will be invalidated.
*
* NOTICE OF LICENSE
*
* This source file is subject to the GNU General Public License (GPLv3)
* It is available through the world-wide-web at this URL:
* http://www.gnu.org/licenses/quick-guide-gplv3.html.en
*/
?>
<?php
/**
 * @see ClipVilla_MorI_Block_Videos
 */
?>
<?php if (Mage::registry('current_product')->getId() == 423) { ?>

    <div itemscope itemtype="http://schema.org/VideoObject" style="max-width: 585px">
        <meta itemprop="name" content="<?php echo $this->getMetaTitle(); ?>">
        <meta itemprop="description" content="<?php echo $this->getMetaDescription(); ?>">
        <meta itemprop="thumbnailUrl" content="<?php echo $this->getImageUrl(); ?>">
        <meta itemprop="contentUrl" content="<?php echo $this->getVideoFile(); ?>">
        <meta itemprop="duration" content="<?php echo $this->getVideoDuration(); ?>">
        <meta itemprop="uploadDate" content="<?php echo $this->getCreationDate(); ?>">
        <video id="product_video" class="video-js vjs-default-skin vjs-big-play-centered"
            controls preload="auto" width="auto" height="auto" data-setup='{}' />
            <source src="http://clipvilla.55.test-dmz-s1-nsd.neusta.de/media/clipvilla/videos/maxi.mp4" type='video/mp4' />
        </video>
    </div>
	
<?php } ?>

<?php if (Mage::registry('current_product')->getId() == 888) { ?>

    <div itemscope itemtype="http://schema.org/VideoObject" style="max-width: 585px">
        <meta itemprop="name" content="<?php echo $this->getMetaTitle(); ?>">
        <meta itemprop="description" content="<?php echo $this->getMetaDescription(); ?>">
        <meta itemprop="thumbnailUrl" content="<?php echo $this->getImageUrl(); ?>">
        <meta itemprop="contentUrl" content="<?php echo $this->getVideoFile(); ?>">
        <meta itemprop="duration" content="<?php echo $this->getVideoDuration(); ?>">
        <meta itemprop="uploadDate" content="<?php echo $this->getCreationDate(); ?>">
        <video id="product_video" class="video-js vjs-default-skin vjs-big-play-centered"
            controls preload="auto" width="auto" height="auto" data-setup='{}' />
            <source src="http://clipvilla.55.test-dmz-s1-nsd.neusta.de/media/clipvilla/videos/electronics.mp4" type='video/mp4' />
        </video>
    </div>
	
<?php } ?>

<?php if (Mage::registry('current_product')->getId() == 414) { ?>

    <div itemscope itemtype="http://schema.org/VideoObject" style="max-width: 585px">
        <meta itemprop="name" content="<?php echo $this->getMetaTitle(); ?>">
        <meta itemprop="description" content="<?php echo $this->getMetaDescription(); ?>">
        <meta itemprop="thumbnailUrl" content="<?php echo $this->getImageUrl(); ?>">
        <meta itemprop="contentUrl" content="<?php echo $this->getVideoFile(); ?>">
        <meta itemprop="duration" content="<?php echo $this->getVideoDuration(); ?>">
        <meta itemprop="uploadDate" content="<?php echo $this->getCreationDate(); ?>">
        <video id="product_video" class="video-js vjs-default-skin vjs-big-play-centered"
            controls preload="auto" width="auto" height="auto" data-setup='{}' />
            <source src="http://clipvilla.55.test-dmz-s1-nsd.neusta.de/media/clipvilla/videos/fashionMan.mp4" type='video/mp4' />
        </video>
    </div>
	
<?php } ?>

<?php if (Mage::registry('current_product')->getId() == 418) { ?>

    <div itemscope itemtype="http://schema.org/VideoObject" style="max-width: 585px">
        <meta itemprop="name" content="<?php echo $this->getMetaTitle(); ?>">
        <meta itemprop="description" content="<?php echo $this->getMetaDescription(); ?>">
        <meta itemprop="thumbnailUrl" content="<?php echo $this->getImageUrl(); ?>">
        <meta itemprop="contentUrl" content="<?php echo $this->getVideoFile(); ?>">
        <meta itemprop="duration" content="<?php echo $this->getVideoDuration(); ?>">
        <meta itemprop="uploadDate" content="<?php echo $this->getCreationDate(); ?>">
        <video id="product_video" class="video-js vjs-default-skin vjs-big-play-centered"
            controls preload="auto" width="auto" height="auto" data-setup='{}' />
            <source src="http://clipvilla.55.test-dmz-s1-nsd.neusta.de/media/clipvilla/videos/fashionWoman.mp4" type='video/mp4' />
        </video>
    </div>
	
<?php } ?>

<?php if (Mage::registry('current_product')->getId() == 447) { ?>

    <div itemscope itemtype="http://schema.org/VideoObject" style="max-width: 585px">
        <meta itemprop="name" content="<?php echo $this->getMetaTitle(); ?>">
        <meta itemprop="description" content="<?php echo $this->getMetaDescription(); ?>">
        <meta itemprop="thumbnailUrl" content="<?php echo $this->getImageUrl(); ?>">
        <meta itemprop="contentUrl" content="<?php echo $this->getVideoFile(); ?>">
        <meta itemprop="duration" content="<?php echo $this->getVideoDuration(); ?>">
        <meta itemprop="uploadDate" content="<?php echo $this->getCreationDate(); ?>">
        <video id="product_video" class="video-js vjs-default-skin vjs-big-play-centered"
            controls preload="auto" width="auto" height="auto" data-setup='{}' />
            <source src="http://clipvilla.55.test-dmz-s1-nsd.neusta.de/media/clipvilla/videos/sale.mp4" type='video/mp4' />
        </video>
    </div>
	
<?php } ?>


<?php if (Mage::registry('current_product')->getId() == 375) { ?>

    <div itemscope itemtype="http://schema.org/VideoObject" style="max-width: 585px">
        <meta itemprop="name" content="<?php echo $this->getMetaTitle(); ?>">
        <meta itemprop="description" content="<?php echo $this->getMetaDescription(); ?>">
        <meta itemprop="thumbnailUrl" content="<?php echo $this->getImageUrl(); ?>">
        <meta itemprop="contentUrl" content="<?php echo $this->getVideoFile(); ?>">
        <meta itemprop="duration" content="<?php echo $this->getVideoDuration(); ?>">
        <meta itemprop="uploadDate" content="<?php echo $this->getCreationDate(); ?>">
        <video id="product_video" class="video-js vjs-default-skin vjs-big-play-centered"
            controls preload="auto" width="auto" height="auto" data-setup='{}' />
            <source src="http://clipvilla.55.test-dmz-s1-nsd.neusta.de/media/clipvilla/videos/circles.mp4" type='video/mp4' />
        </video>
    </div>
	
<?php } ?>

<?php if($this->videoExists()): ?>
    <div itemscope itemtype="http://schema.org/VideoObject" style="max-width: 585px">
        <meta itemprop="name" content="<?php echo $this->getMetaTitle(); ?>">
        <meta itemprop="description" content="<?php echo $this->getMetaDescription(); ?>">
        <meta itemprop="thumbnailUrl" content="<?php echo $this->getImageUrl(); ?>">
        <meta itemprop="contentUrl" content="<?php echo $this->getVideoFile(); ?>">
        <meta itemprop="duration" content="<?php echo $this->getVideoDuration(); ?>">
        <meta itemprop="uploadDate" content="<?php echo $this->getCreationDate(); ?>">
        <video id="product_video" class="video-js vjs-default-skin vjs-big-play-centered"
            controls preload="auto" width="auto" height="auto" data-setup='{}' />
            <source src="<?php echo $this->getVideoFile(); ?>" type='video/mp4' />
        </video>
    </div>
<?php endif ?>
